# Generated by Django 4.2.4 on 2023-08-31 14:59

import VaiStore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='App', help_text='Укажите название приложения', max_length=30)),
                ('app_id', models.CharField(default='AppID', help_text='Укажите айди приложения, по типу TheGame', max_length=200)),
                ('app_size', models.CharField(default='30', help_text='Укажите размер приложения', max_length=4)),
                ('author', models.CharField(default='SuperStudio', help_text='Укажите разработчикаю приложения', max_length=50)),
                ('description', models.CharField(default='The Game 2.0', help_text='Укажите описание приложения', max_length=400)),
                ('image', models.ImageField(help_text='Выберите картинку, png', upload_to=VaiStore.models.file_path)),
                ('link', models.CharField(default='https://example.com/Game.apk', help_text='Ссылка на приложение', max_length=500)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('app_id',),
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=4)),
                ('changes', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AppScreenShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=VaiStore.models.file_path)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='VaiStore.app')),
            ],
        ),
    ]
